# This is a basic workflow to help you get started with Actions

name: "build mise"

# Controls when the workflow will run
on:
  # copr build mise every day.
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mise:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout to execute local action
        uses: actions/checkout@v4
      - name: setup modules
        run: |
          pip3 install copr
      - name: copr-build
        uses: akdev1l/copr-build@main
        id: mise
        env:
          COPR_API_TOKEN_CONFIG: ${{ secrets.COPR_API_TOKEN_CONFIG }}
        with:
          owner: ${{ secrets.OWNER }}
          package-name: mise
          project-name: tools
